---

# Install Python
- import_tasks: python.yml

# Install Git
- import_tasks: git.yml

# Install Ansible
- import_tasks: ansible.yml

# Install Packer
- import_tasks: packer.yml

# Install Terraform
- import_tasks: terraform.yml

# Install AWS CLI
- import_tasks: aws-cli.yml

# Install Code-Server
- import_tasks: code-server.yml

# Output Code-Server config details
- import_tasks: output.yml